#######
#Simpager
#######
CXX = g++
CXXFLAGS = -O2

###
#   $^ - "all the dependencies"
#   $< - "the first dependency"
#   $@ - "the target name"



simpager: main.o fifo.o lru.o opt.o rand.o
	$(CXX) $(CXXFLAGS) -o $@ $^

main.o: main.cpp
	$(CXX) $(CXXFLAGS) -c $<

fifo.o: fifo.cpp
	$(CXX) $(CXXFLAGS) -c $<

lru.o: lru.cpp
	$(CXX) $(CXXFLAGS) -c $<

opt.o: opt.cpp
	$(CXX) $(CXXFLAGS) -c $<

rand.o: rand.cpp
	$(CXX) $(CXXFLAGS) -c $<

clean:
	/bin/rm -f *.o  simpager
